version: "3.9"

services:
  redis:
    image: redis:7.0.11-alpine3.18
    volumes:
      - redis_db:/var/lib/postgresql/data
    networks:
      - main
  backend:
    build: ./backend
    depends_on:
      - redis
    ports:
      - "80:80"
    networks:
      - main
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - main

volumes:
  redis_db:
networks:
  main:

