version: "3.9"

services:
  redis:
    image: redis:7.0.11-alpine3.18
    volumes:
      - redis_db:/var/lib/postgresql/data
  backend:
    container_name: backend
    build: ./backend
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "8000:80"
  frontend:
    container_name: frontend
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  redis_db:
