version: "3.9"

services:
  redis:
    image: redis:7.0.11-alpine3.18
    volumes:
      - redis_db:/var/lib/postgresql/data
    networks:
      - main
  backend:
    container_name: backend
    build: ./backend
    env_file:
      - .env
    depends_on:
      - redis
    # TODO: hide backend
    ports:
      - "8000:80"
    networks:
      - main
  frontend:
    container_name: frontend
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - main

volumes:
  redis_db:
networks:
  main:
