
FROM python:3.12.4-alpine3.20

COPY ./requirements.txt /requirements.txt
RUN python -m pip install --upgrade pip
RUN pip install --upgrade -r /requirements.txt

COPY . /app

CMD [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80" ]
